### ISSUE TITLE
Maybe use external library for JWT handeling

### ISSUE THREAD

**Issue by choffmeister** [choffmeister/auth-utils#3]
The library [jose4j](https://bitbucket.org/b_c/jose4j/wiki/Home) has support for many hashing algorithms as well as encryption on JSON web tokens. Maybe it would be useful, to drop the custom JWT implementation and use that instead.

**Comment by neowit** [comment]
+1
Security experts usually advise to use a well established library. Not that I know of any expert reviews of jose4j, but it has been around for a while and some of the most obvious problems have already been fixed.
Besides, there is no point in duplicating efforts.

**Comment by choffmeister** [comment]
The JWT part of this library is deprecated. I build a new one in one of my new libraries here: https://github.com/choffmeister/microservice-utils/blob/master/microservice-utils/src/main/scala/de/choffmeister/microserviceutils/http/JsonWebTokenAuthenticator.scala

It uses jjwt under the hood. So from this library basically only the password hasher should still be used.

**Comment by choffmeister** [comment]
I added a deprecation leading to an alternative using jjwt. So I guess this can be closed.
